import type { Metadata } from "next";
import { Mulish, Capriola } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
 
const capriola = Capriola({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-capriola',
  fallback:['sans-sarif']
})

const mulish = Mulish({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-mulish',
  fallback:['sans-sarif']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${capriola.variable} ${mulish.variable}`}>
      <body>
        <main className='w-full h-full '>
            <Providers>
              {children}
            </Providers>
        </main>
      </body>
    </html>
  );
}
